# Generated by Django 5.0 on 2024-01-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='content',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
